DROP DATABASE IF EXISTS EXAMENDB;
CREATE DATABASE IF NOT EXISTS EXAMENDB;
USE EXAMENDB;

CREATE TABLE UNIDADDIDACTICA (
ID INT PRIMARY KEY,
ACRONIMO VARCHAR(50),
TITULO VARCHAR(100),
EVALUACION VARCHAR(50),
DESCRIPCION VARCHAR(150)
);


CREATE TABLE ENUNCIADO (
ID INT PRIMARY KEY,
DESCRIPCION VARCHAR(50),
NIVEL ENUM('ALTA', 'MEDIA', 'BAJA'),
DISPONIBLE BOOL,
RUTA VARCHAR(50)
);


CREATE TABLE UNIDADENUNCIADO (
UNIDADID INT,
ENUNCIADOID INT,
PRIMARY KEY (UNIDADID,ENUNCIADOID),
FOREIGN KEY (UNIDADID) REFERENCES UNIDADDIDACTICA(ID) ON DELETE CASCADE,
FOREIGN KEY (ENUNCIADOID) REFERENCES ENUNCIADO(ID) ON DELETE CASCADE
);


CREATE TABLE CONVOCATORIAEXAMEN (
ID INT PRIMARY KEY,
CONVOCATORIA VARCHAR(50),
DESCRIPCION VARCHAR(50),
FECHA DATE,
CURSO VARCHAR(50),
ENUNCIADOID INT,
FOREIGN KEY (ENUNCIADOID) REFERENCES ENUNCIADO(ID) ON DELETE CASCADE
);